name: ros2_nubots

services:
  ros2:
    image: nubots/nubots_ros2_booster
    build: ./docker
    runtime: nvidia
    gpus: all
    network_mode: host
    shm_size: 8g
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,graphics,utility,display
      - DISPLAY=${DISPLAY}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - QT_X11_NO_MITSHM=1
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
      - HOME=/home/nubots
      - USER=nubots
    volumes:
        - type: bind
          source: .
          target: /home/nubots/ros2_ws
          read_only: false
        - type: bind
          source: /tmp/.X11-unix
          target: /tmp/.X11-unix
        - type: bind
          source: ${XDG_RUNTIME_DIR}
          target: ${XDG_RUNTIME_DIR}
          read_only: false
        - type: bind
          source: /home/zeonyph/.local/share/ov/pkg
          target: /home/nubots/.local/share/ov/pkg
          read_only: false
        - type: bind
          source: /home/zeonyph/.cache/ov
          target: /home/nubots/.cache/ov
          read_only: false
        - type: bind
          source: /home/zeonyph/.cache/pip
          target: /home/nubots/.cache/pip
          read_only: false
        - type: bind
          source: /home/zeonyph/.cache/nvidia/GLCache
          target: /home/nubots/.cache/nvidia/GLCache
          read_only: false
        - type: bind
          source: /home/zeonyph/.nv/ComputeCache
          target: /home/nubots/.nv/ComputeCache
          read_only: false
        - type: bind
          source: /home/zeonyph/.local/share/ov/data
          target: /home/nubots/.local/share/ov/data
          read_only: false
        - type: bind
          source: /home/zeonyph/Documents
          target: /home/nubots/Documents
          read_only: false
    tty: true
    stdin_open: true
    command: bash -c 'echo -e "Container running, access via another terminal by using \033[32;1;4mdocker compose exec -it ros2 bash\033[0m" && sleep infinity'